# Generated by Django 4.2.8 on 2024-01-04 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('linkedin', 'Linkedin'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('github', 'Github'), ('bitbucket', 'Bitbucket'), ('gitlab', 'Gitlab'), ('outro', 'Outro')], default='outro', max_length=200)),
                ('link', models.CharField(blank=True, max_length=5000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('github', 'Github'), ('bitbucket', 'Bitbucket'), ('gitlab', 'Gitlab'), ('outro', 'Outro')], default='outro', max_length=200, unique=True)),
                ('link', models.CharField(blank=True, choices=[('github', 'Github'), ('bitbucket', 'Bitbucket'), ('gitlab', 'Gitlab'), ('outro', 'Outro')], max_length=5000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=5000, null=True)),
                ('link', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InformacaoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacao', models.CharField(max_length=5000, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intituicao', models.CharField(max_length=200)),
                ('curso', models.CharField(default='em_curso', max_length=200)),
                ('nivel_de_ensino', models.CharField(choices=[('profissionalizante', 'Profissionalizante'), ('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo'), ('graduacao', 'Graduação'), ('pos_graduacao', 'Pós-Graduação'), ('Superior', 'Superior'), ('outro', 'Outro')], default='outro', max_length=200)),
                ('periodo_inicio', models.DateField()),
                ('periodo_final', models.DateField(blank=True, null=True)),
                ('situacao', models.TextField(choices=[('completo', 'Completo'), ('interrompido', 'Interrompido'), ('em_curso', 'Em Curso')], max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=5000)),
                ('periodo_inicio', models.DateField()),
                ('periodo_final', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('phone', 'Telefone'), ('email', 'Email'), ('wp', 'Whatsapp'), ('outro', 'Outro')], default='outro', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcaoVisitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('view', 'Visualização'), ('print', 'Impressão'), ('wp', 'Envio Menssagem no Whatsapp'), ('email', 'Envio Menssagem no Email')], default='view', max_length=200)),
                ('usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True)),
                ('geo_location', models.CharField(blank=True, max_length=200, null=True)),
                ('device_vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Smartphone'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('tv', 'SmartTV')], max_length=200, null=True)),
                ('device_browser', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
