FROM node:lts-alpine

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./ui/. .

# install project dependencies and build app for production with minification
RUN npm install &&  npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]

RUN echo "Web UI build Successfully!"