FROM node:lts-alpine

# Install simple http server for serving static content
RUN npm install -g http-server

# Make the 'app' folder the current working directory
WORKDIR /app

# Copy both 'package.json' and 'package-lock.json' (if available)
COPY ./ui/. .

# Install project dependencies and build app for production with minification
RUN npm install && npm run build

# Expose server port
EXPOSE 8080

#Satart project with command: CMD [ "http-server", "dist" ] or CMD [ "npm", "run", "serve" ]
CMD [ "npm", "run", "serve" ]

RUN echo "Web UI build Successfully!"